@startuml "Consult team"
skinparam style strictuml

actor Lead as U
boundary "Teams.routes.js" as RO
boundary "View: teamsList.ejs" as VL
boundary "View: teamsEdit.ejs" as VE
control "teams.controller" as C
entity "teams.model" as TM
database "MySQL" as BD

' Section about getting a list of teams '
activate U
U -> RO : GET /teams/list
deactivate U

activate RO
RO -> C : getList(request, response)
deactivate RO

activate C
C -->> TM : getAllWithMemberCount()
activate TM
TM -->> BD : SELECT \nt.team_id, \nt.team_name, \nt.team_start_date, \nCOUNT(ut.user_id) as memberCount \nFROM Team t \nLEFT JOIN User_Team ut ON t.team_id = ut.team_id \nWHERE t.deleted_at IS NULL \nGROUP BY t.team_id, t.team_name, t.team_start_date \nORDER BY t.team_name ASC`

deactivate BD
TM -->> C : teams
deactivate TM

alt teams.length == 0
C -> VL : response.render('teamList', {teams: [], message: 'No teams available'})

activate VL
VL -> U : html
deactivate VL
end

C -> VL : response.render('teamList', teams)
deactivate C

activate VL
VL -> U : html
deactivate VL
